export const DEFAULT_PERMISSIONS = [
  ['branch.view', 'branch', 'view', 'View assigned branches'],
  ['branch.switch', 'branch', 'switch', 'Switch between assigned branches'],
  ['product.view', 'product', 'view', 'View products'],
  ['product.create', 'product', 'create', 'Create products'],
  ['product.update', 'product', 'update', 'Update products'],
  ['product.archive', 'product', 'archive', 'Archive products'],
  ['purchase.view', 'purchase', 'view', 'View purchases'],
  ['purchase.create', 'purchase', 'create', 'Create purchases'],
  ['purchase.approve', 'purchase', 'approve', 'Approve purchases'],
  ['purchase.receive', 'purchase', 'receive', 'Receive purchases'],
  ['sales.view', 'sales', 'view', 'View sales'],
  ['sales.create', 'sales', 'create', 'Create sales'],
  ['sales.return', 'sales', 'return', 'Process sales returns'],
  ['sales.refund', 'sales', 'refund', 'Process sales refunds'],
  ['stock.view', 'stock', 'view', 'View stock'],
  ['stock.adjust', 'stock', 'adjust', 'Adjust stock'],
  ['stock.opname', 'stock', 'opname', 'Run stock opname'],
  ['stock.transfer', 'stock', 'transfer', 'Transfer stock'],
  ['report.sales', 'report', 'sales', 'View sales reports'],
  ['report.profit', 'report', 'profit', 'View profit reports'],
  ['prescription.view', 'prescription', 'view', 'View prescriptions'],
  ['prescription.create', 'prescription', 'create', 'Create prescriptions'],
  ['prescription.dispense', 'prescription', 'dispense', 'Dispense prescriptions'],
  ['user.manage', 'user', 'manage', 'Manage users'],
  ['role.manage', 'role', 'manage', 'Manage roles and permissions'],
  ['settings.manage', 'settings', 'manage', 'Manage tenant settings'],
] as const;

export type PermissionCode = (typeof DEFAULT_PERMISSIONS)[number][0];
